src/Swetugg.Web/Models/Conference.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Swetugg.Web.Models
{
    public class Conference
    {
        public int Id { get; set; }

        [Required]
        [StringLength(250)]
        public string Name { get; set; }

        [Required]
        [StringLength(250)]
        public string Slug { get; set; }

        [DataType(DataType.MultilineText)]
        [Column(TypeName = "ntext")]
        public string Description { get; set; }

        [DisplayFormat(DataFormatString = "{0:yyyy-MM-dd}",
               ApplyFormatInEditMode = true)]
        public DateTime? Start { get; set; }

        [DisplayFormat(DataFormatString = "{0:yyyy-MM-dd}",
               ApplyFormatInEditMode = true)]
        public DateTime? End { get; set; }

        [DisplayFormat(DataFormatString = "{0:yyyy-MM-dd}",
                ApplyFormatInEditMode = true)]
        public DateTime? CfpEnd { get; set; }

        [Display(Name = "Min speakers on front page")]
        public int MinNumberOfSpeakers { get; set; }
        
        [Display(Name = "Sessionize API code")]
        public string SessionizeAPICode { get; set; }

        public ICollection<Speaker> Speakers { get; set; }
        public ICollection<Session> Sessions { get; set; }
        public ICollection<Sponsor> Sponsors { get; set; }
        public ICollection<Slot> Slots { get; set; }
        public ICollection<Room> Rooms { get; set; }
        public ICollection<ImageType> ImageTypes { get; set; }
        public ICollection<SessionType> SessionTypes { get; set; }


    }
}

src/Swetugg.Web/Areas/Gbg2022/Controllers/ConferenceController.cs
using System;
using System.Configuration;
using System.Globalization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Caching.Memory;
using Swetugg.Web.Models;
using Swetugg.Web.Services;

namespace Swetugg.Web.Areas.Gbg2022.Controllers
{
    [Area("Gbg2022")]
    public class ConferenceController : Microsoft.AspNetCore.Mvc.Controller
    {
        private readonly IConferenceService conferenceService;

        private int conferenceId;
        private string conferenceSlug;
        private Conference conference;
        private string appInsightsInstrumentationKey;
        private string facebookAppId;

        public ConferenceController(ApplicationDbContext dbContext, IMemoryCache memoryCache)
        {
            this.conferenceSlug = "gbg-2022";
            this.conferenceService = new CachedConferenceService(new ConferenceService(dbContext), memoryCache);
            this.appInsightsInstrumentationKey = ConfigurationManager.AppSettings["ApplicationInsights.InstrumentationKey"];
            this.facebookAppId = ConfigurationManager.AppSettings["Facebook_Api_AppId"];
        }

        // TODO: Inject app insights and facebook ids to view
        //protected override void OnResultExecuting(Microsoft.AspNetCore.Mvc.Filters.ResultExecutingContext filterContext)
        //{
        //    ViewData["InstrumentationKey"] = appInsightsInstrumentationKey;
        //    ViewData["FacebookAppId"] = facebookAppId;
        //    base.OnResultExecuting(filterContext);
        //}

        [Route("")]
        public Microsoft.AspNetCore.Mvc.ActionResult Index()
        {
            var conf = Conference;
            if (conf == null)
            {
                return NotFound();
            }

            var speakers = conferenceService.GetSpeakers(conf.Id);
            var sessions = conferenceService.GetSessions(conf.Id);
            var slots = conferenceService.GetSlotsAndSessions(conf.Id);
            var rooms = conferenceService.GetRooms(conf.Id);
            var sponsors = conferenceService.GetSponsors(conf.Id);
            var speakerImages = conferenceService.GetSpeakerImages(conf.Id);

            ViewData["Speakers"] = speakers;
            ViewData["Sessions"] = sessions;
            ViewData["Slots"] = slots;
            ViewData["Rooms"] = rooms;
            ViewData["Sponsors"] = sponsors;
            ViewData["Conference"] = conf;
            ViewData["SpeakerImages"] = speakerImages;

            bool ticketSalesOpen;
            
            // Do we have forced open/close info for ticket sales?
            if (!bool.TryParse(ConfigurationManager.AppSettings["Ticket_Sales_Force"], out ticketSalesOpen))
            {
                // No forced info. Let's see if we have an open date/time
                DateTime ticketsOpenDateTime;
                if (DateTime.TryParse(ConfigurationManager.AppSettings["Ticket_Sales_Open_Date"], 
                    CultureInfo.InvariantCulture,
                    DateTimeStyles.None, out ticketsOpenDateTime))
                {
                    // Ticket sales should be open if the local conference time is greater than the date/time
                    ticketSalesOpen = conference.CurrentTime() > ticketsOpenDateTime;
                }
            }

            bool conferenceOngoing = false;
            if (conference.Start.HasValue && conference.End.HasValue)
            {
                var currentTime = conference.CurrentTime();
                conferenceOngoing = currentTime > conference.Start.Value.Date &&
                                    currentTime < conference.End.Value.Date.AddDays(1);
            }

            ViewData["TicketSalesOpen"] = ticketSalesOpen;
            ViewData["ConferenceOngoing"] = conferenceOngoing;
            ViewData["TicketUrl"] = ConfigurationManager.AppSettings["Ticket_Url"];
            ViewData["TicketKey"] = ConfigurationManager.AppSettings["Ticket_Key"];
            ViewData["SponsorTicketKey"] = ConfigurationManager.AppSettings["SponsorTicket_Key"];

            return View();
        }

        [Route("now")]
        public Microsoft.AspNetCore.Mvc.ActionResult Now()
        {
            var conf = Conference;
            if (conf == null)
            {
                return NotFound();
            }

            var sponsors = conferenceService.GetSponsors(conf.Id);
            ViewData["Sponsors"] = sponsors;

            return View();
        }

        [Route("code-of-conduct")]
        public Microsoft.AspNetCore.Mvc.ActionResult CodeOfConduct()
        {
            ViewData["Conference"] = Conference;
            return View();
        }

        [Route("speakers/{speakerSlug}")]
        public Microsoft.AspNetCore.Mvc.ActionResult Speaker(string speakerSlug)
        {
            var speaker = conferenceService.GetSpeakerBySlug(ConferenceId, speakerSlug);
            if (speaker == null)
            {
                return NotFound();
            }

            return View(speaker);
        }

        public override void OnActionExecuted(Microsoft.AspNetCore.Mvc.Filters.ActionExecutedContext context)
        {
            ViewBag.Conference = Conference;
            base.OnActionExecuted(context);
        }

        protected Conference Conference
        {
            get
            {
                if (conference != null)
                    return conference;

                return conference = conferenceService.GetConferenceBySlug(ConferenceSlug);
            }

        }
        protected int ConferenceId
        {
            get
            {
                if (conferenceId != 0)
                    return conferenceId;

                if (Conference == null)
                    return 0;

                return conferenceId = Conference.Id;
            }
        }

        protected string ConferenceSlug
        {
            get
            {
                if (conferenceSlug != null)
                    return conferenceSlug;

                return conferenceSlug = (string)RouteData.Values["conferenceSlug"];
            }
        }

    }
}

src/Swetugg.Web/Controllers/CallForPapersController.cs
using System;
using System.Configuration;
using System.Data.Entity;
using System.Drawing;
using System.Drawing.Imaging;
using System.IO;
using System.Linq;
using System.Runtime.InteropServices;
using System.Threading.Tasks;
using System.Web;
using System.Web.Instrumentation;
using System.Web.Mvc;
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.Owin;
using Microsoft.WindowsAzure;
using Microsoft.WindowsAzure.Storage;
using Microsoft.WindowsAzure.Storage.Auth;
using Microsoft.WindowsAzure.Storage.Blob;
using Swetugg.Web.Models;
using Swetugg.Web.Services;

namespace Swetugg.Web.Controllers
{

    [RequireHttps]
    [RoutePrefix("cfp")]
    [Authorize()]
    public class CallForPapersController : Controller
    {
        private readonly IConferenceService _conferenceService;
        private readonly IImageUploader _imageUploader;
        private ApplicationUserManager _userManager;
        private ApplicationSignInManager _signInManager;
        private readonly ApplicationDbContext _dbContext;
        private readonly string _cfpSpeakerImageContainerName;

        public CallForPapersController(IConferenceService conferenceService, IImageUploader imageUploader, ApplicationDbContext dbContext)
        {
            _conferenceService = conferenceService;
            _imageUploader = imageUploader;
            _dbContext = dbContext;
            _cfpSpeakerImageContainerName = ConfigurationManager.AppSettings["Storage.Container.CallForPaper.SpeakerImages"];
        }

        public ApplicationUserManager UserManager
        {
            get
            {
                return _userManager ?? HttpContext.GetOwinContext().GetUserManager<ApplicationUserManager>();
            }
            private set
            {
                _userManager = value;
            }
        }

        public ApplicationSignInManager SignInManager
        {
            get
            {
                return _signInManager ?? HttpContext.GetOwinContext().Get<ApplicationSignInManager>();
            }
            private set
            {
                _signInManager = value;
            }
        }


        [Route("")]
        public ActionResult Index()
        {
            var userId = User.Identity.GetUserId();
            var conferences = _conferenceService.GetConferences().Where(c => c.End == null || c.End >= c.CurrentTime().Date);
            var cfpAlreadyCreatedFor = _dbContext.CfpSpeakers.Where(sp => sp.UserId == userId).Select(sp=>sp.ConferenceId).ToArray();

            ViewBag.CfpAlreadyCreatedFor = cfpAlreadyCreatedFor;

            return View(conferences);
        }


        [Route("{conferenceSlug}/vip-invite/{code}")]
        public async Task<ActionResult> Invite(string conferenceSlug, string code)
        {
            var conference = _conferenceService.GetConferenceBySlug(conferenceSlug);

            if (conference.CfpVipCode.Equals(code, StringComparison.InvariantCultureIgnoreCase))
            {
                var userId = User.Identity.GetUserId();
                var user = UserManager.FindById(userId);
                
                await UserManager.AddToRoleAsync(userId, "VipSpeaker");
                await SignInManager.SignInAsync(user, false, false); // Sign in again
                ViewBag.Success = true;
            }
            else
            {
                ViewBag.Success = false;
            }

            ViewBag.Conference = conference;
            return View(conference);
        }

        [Route("{conferenceSlug}")]
        public ActionResult Conference(string conferenceSlug)
        {
            var conference = _conferenceService.GetConferenceBySlug(conferenceSlug);
            var userId = User.Identity.GetUserId();
            var speaker = _dbContext.CfpSpeakers.Include(sp => sp.Sessions).SingleOrDefault(sp => sp.UserId == userId && sp.ConferenceId == conference.Id);
            if (speaker == null)
            {
                if (User.IsAllowedToCreateCfp(conference))
                {
                    return RedirectToAction("Speaker");
                }
                else
                {
                    return RedirectToAction("Index");
                }
            }
            ViewBag.Conference = conference;

            return View(speaker);
        }

        [Route("{conferenceSlug}/speaker")]
        public ActionResult Speaker(string conferenceSlug)
        {
            var conference = _conferenceService.GetConferenceBySlug(conferenceSlug);
            var userId = User.Identity.GetUserId();
            var speaker = _dbContext.CfpSpeakers.Include(sp => sp.Sessions).SingleOrDefault(sp => sp.UserId == userId && sp.ConferenceId == conference.Id);
            if (speaker == null)
            {
                if (!User.IsAllowedToCreateCfp(conference))
                {
                    // CFP Isn't open. Can't create new speakers.
                    return RedirectToAction("Index");
                }
                speaker = new CfpSpeaker()
                {
                    Email = User.Identity.Name
                };
            }
            ViewBag.Conference = conference;

            return View(speaker);
        }

        [Route("{conferenceSlug}/speaker")]
        [HttpPost]
        public ActionResult Speaker(string conferenceSlug, CfpSpeaker speaker, HttpPostedFileBase imageFile)
        {
            var conference = _conferenceService.GetConferenceBySlug(conferenceSlug);
            var userId = User.Identity.GetUserId();
            
            if (ModelState.IsValid)
            {
                try
                {
                    var dbSpeaker = 
                        _dbContext.CfpSpeakers.SingleOrDefault(sp => sp.UserId == userId && sp.ConferenceId == conference.Id);

                    if (dbSpeaker == null)
                    {
                        if (!User.IsAllowedToCreateCfp(conference))
                        {
                            // CFP Isn't open. Can't create new speakers.
                            return RedirectToAction("Index");
                        }
                        dbSpeaker = new CfpSpeaker();
                        _dbContext.Entry(dbSpeaker).State = EntityState.Added;
                        dbSpeaker.UserId = userId;
                    }
                    dbSpeaker.ConferenceId = conference.Id;
                    dbSpeaker.Bio = speaker.Bio;
                    dbSpeaker.Company = speaker.Company;
                    dbSpeaker.Email = speaker.Email;
                    dbSpeaker.GitHub = speaker.GitHub;
                    dbSpeaker.Name = speaker.Name;
                    dbSpeaker.Twitter = speaker.Twitter;
                    dbSpeaker.Web = speaker.Web;
                    dbSpeaker.Comments = speaker.Comments;
                    dbSpeaker.NeedTravel = speaker.NeedTravel;
                    dbSpeaker.NeedAccommodation = speaker.NeedAccommodation;

                    if (imageFile != null && imageFile.ContentLength > 0)
                    {
                        if (imageFile.ContentLength < 10*1024*1024)
                        {
                            try
                            {
                                using (var memStream = new MemoryStream())
                                {
                                    imageFile.InputStream.CopyTo(memStream);
                                    var imageUrl = _imageUploader.UploadToStorage(memStream, dbSpeaker.Email, _cfpSpeakerImageContainerName);
                                    dbSpeaker.Image = imageUrl;
                                }
                            }
                            catch (ImageUploadException e)
                            {
                                ModelState.AddModelError("ImageFile", e.Message);
                            }
                        }
                        else
                        {
                            ModelState.AddModelError("ImageFile", "Max file size of image is ~10MB");
                        }
                    }
                    // If there are still no errors
                    if (ModelState.IsValid)
                    {
                        _dbContext.SaveChanges();

                        return RedirectToAction("Conference");
                    }
                }
                catch (Exception ex)
                {
                    ModelState.AddModelError("Saving", ex);
                }
            }

            ViewBag.Conference = conference;
            return View(speaker);
        }

        [Route("{conferenceSlug}/session")]
        #pragma warning disable 0108
        public ActionResult Session(string conferenceSlug, int? id)
        #pragma warning restore 0108
        {
            var conference = _conferenceService.GetConferenceBySlug(conferenceSlug);
            var userId = User.Identity.GetUserId();
            var speaker = _dbContext.CfpSpeakers.Include(sp => sp.Sessions).SingleOrDefault(sp => sp.UserId == userId && sp.ConferenceId == conference.Id);

            CfpSession session;
            if (id.HasValue)
            {
                session = speaker.Sessions.SingleOrDefault(s => s.Id == id);
            }
            else
            {
                if (!User.IsAllowedToCreateCfp(conference))
                {
                    // CFP Isn't open. Can't create new sessions.
                    return RedirectToAction("Conference");
                }
                session = new CfpSession() { Speaker = speaker };
            }

            ViewBag.Conference = conference;
            ViewBag.Speaker = speaker;

            return View(session);
        }
        

        [Route("{conferenceSlug}/session")]
        [HttpPost]
        #pragma warning disable 0108
        public ActionResult Session(string conferenceSlug, int? id, CfpSession session)
        #pragma warning restore 0108
        {

src/Swetugg.Web/Views/CallForPapers/Conference.cshtml
@using Swetugg.Web.Models
@using Swetugg.Web.Helpers
@model CfpSpeaker

@{
    Conference conference = ViewBag.Conference;
    
    ViewBag.Title = conference.Name + " - Call For Papers";
}
<ol class="breadcrumb">
    <li>@Html.ActionLink("Start", "Start", "Home", new { Area = "" }, null)</li>
    <li>@Html.ActionLink("Call For Papers", "Index", "CallForPapers", new { Area = "" }, null)</li>
    <li class="active">@conference.Name</li>
</ol>


<div class="panel panel-default">
    <div class="panel-heading">
        <h3>@conference.Name</h3>
    </div>
    <div class="panel-body">
        <div class="row">
            <div class="col-sm-2">
                <img src="@Model.Image" class="img-rounded img-responsive" />
            </div>
            <div class="col-sm-6">
                <h3>@Model.Name</h3>
                <p>@Html.Raw(Html.FromMarkdown(Model.Bio))</p>
            </div>
            <div class="col-sm-4">
                <div class="panel panel-info">
                    <div class="panel-heading">
                        <div class="panel-title">Sessions</div>
                    </div>
                    <div class="list-group">
                        @foreach (var session in Model.Sessions)
                        {
                            <div class="list-group-item">
                                @Html.ActionLink(session.Name, "Session", "CallForPapers", new {id = session.Id}, null)
                            </div>
                        }
                    </div>
                    <div class="panel-footer">
                        @Html.ActionLink("Add", "Session", "CallForPapers", null, new {@class = "btn btn-default"})
                    </div>
                </div>

                <div class="panel panel-info">
                    <div class="panel-heading">
                        <div class="panel-title">Information</div>
                    </div>
                    <div class="panel-body">
                        <h4>Company</h4>
                        <p>@Model.Company</p>

                        <h4>Twitter</h4>
                        <p><a href="https://twitter.com/@Model.Twitter">@@@Model.Twitter</a></p>

                        <h4>Email</h4>
                        <p><a href="mailto:@Model.Email">@Model.Email</a></p>

                        <h4>Web</h4>
                        <p><a href="@Model.Web.EnsureHttpLink()">@Model.Web</a></p>

                        <h4>GitHub</h4>
                        <p><a href="https://github.com/@Model.GitHub">@Model.GitHub</a></p>

                        <h4>Comments</h4>
                        <p>@Model.Comments</p>
                    </div>
                </div>

            </div>
        </div>
    </div>
    <div class="panel-footer">
        @Html.ActionLink("Edit", "Speaker", new { }, new { @class = "btn btn-default" })

        <a href="" class="btn btn-danger pull-right"
           data-confirm-form="#deleteForm"
           data-modal-title="Are you sure?"
           data-modal-message="This will delete all your submission data including any sessions you have entered."
           data-toggle="modal" data-target="#formConfirmationModal"><i class="glyphicon glyphicon-trash"></i>&nbsp;Delete</a>
    </div>
</div>

@using (Html.BeginForm("DeleteSpeaker", "CallForPapers", new { conferenceSlug = conference.Slug }, FormMethod.Post, new { id = "deleteForm", @class = "form-inline" }))
{
}

src/Swetugg.Web/Views/CallForPapers/Invite.cshtml
@using Swetugg.Web.Models
@model dynamic

@{
    Conference conference = ViewBag.Conference;

    ViewBag.Title = conference.Name + " - Call For Papers - Invite";
}
<ol class="breadcrumb">
    <li>@Html.ActionLink("Start", "Start", "Home", new { Area = "" }, null)</li>
    <li>@Html.ActionLink("Call For Papers", "Index", "CallForPapers", new { Area = "" }, null)</li>
    <li>@Html.ActionLink(conference.Name, "Conference", "CallForPapers", new { Area = "", conferenceSlug = conference.Slug }, null)</li>
    <li class="active">Invite</li>
</ol>

<h2>Call For Papers - Invite</h2>

@if (ViewBag.Success)
{
    <p>
        You are now allowed to add sessions event though the CFP has ended.
    </p>
    <p>
        Head to the @Html.ActionLink(conference.Name + " CFP site", "Conference") and enter your information.
    </p>
}
else
{
    <p class="warning">Sorry, invalid invitation code</p>
}

src/Swetugg.Web/Views/CallForPapers/Session.cshtml
@using Swetugg.Web.Models
@model Swetugg.Web.Models.CfpSession

@{
    Conference conference = ViewBag.Conference;
    CfpSpeaker speaker = ViewBag.Speaker;
    ViewBag.Title = conference.Name + " - Call For Papers - " + speaker.Name;
}
<ol class="breadcrumb">
    <li>@Html.ActionLink("Start", "Start", "Home", new {Area = ""}, null)</li>
    <li>@Html.ActionLink("Call For Papers", "Index", "CallForPapers", new {Area = ""}, null)</li>
    <li>@Html.ActionLink(conference.Name, "Conference", "CallForPapers", new {Area = "", conferenceSlug = conference.Slug}, null)</li>
    <li class="active">Session</li>
</ol>

@Html.ValidationSummary()

@helper Popover(string title, string content)
{
    <a class=""
       data-toggle="popover"
       data-placement="top"
       data-trigger="hover"
       title="@title"
       data-html="true"
       data-content="@content"><i class="glyphicon glyphicon-info-sign"></i></a>
}

<div class="panel panel-default">
    <div class="panel-heading">
        <h3>Session information</h3>
    </div>

    @using (Html.BeginForm(new {id = Model.Id}))
    {
        <div class="panel-body">
            <div class="row">
                <div class="col-sm-8">
                    <div class="form-group">
                        @Html.LabelFor(m => m.Name)
                        @Html.TextBoxFor(m => m.Name, new {@class = "form-control"})
                        @Html.ValidationMessageFor(m => m.Name)
                    </div>
                    <div class="form-group">
                        @Html.LabelFor(m => m.Description)
                        @Popover("Description", "Please write the session description in the language you will be presenting. Note that the main language of the Swetugg conference is Swedish.")
                        @Html.TextAreaFor(m => m.Description, new {@class = "form-control", rows = 18})
                        @Html.ValidationMessageFor(m => m.Description)
                    </div>
                </div>
                <div class="col-sm-4">
                    <div class="panel panel-info">
                        <div class="panel-heading">
                            <div class="panel-title">More info</div>
                        </div>
                        <div class="panel-body">
                            <div class="form-group">
                                @Html.LabelFor(m => m.Tags)
                                @Popover("Tags", "Comma-separated list of suitable tags for your session. <br />Example 'asp.net, c#, architecture'")
                                @Html.TextBoxFor(m => m.Tags, new {@class = "form-control"})
                                @Html.ValidationMessageFor(m => m.Tags)
                            </div>
                            <div class="form-group">
                                @Html.LabelFor(m => m.Audience)
                                @Popover("Intended audience", "Who should come see your session? <br />Example 'Developers, Architects'")
                                @Html.TextBoxFor(m => m.Audience, new {@class = "form-control"})
                                @Html.ValidationMessageFor(m => m.Audience)
                            </div>
                            <div class="form-group">
                                @Html.LabelFor(m => m.Level)
                                @Popover("Difficulty level", @"What level is your session? <br />Example 'Introduction', 'Intermediate', 'Advanced'")
                                @Html.TextBoxFor(m => m.Level, new {@class = "form-control"})
                                @Html.ValidationMessageFor(m => m.Level)
                            </div>
                            <div class="form-group">
                                @Html.LabelFor(m => m.Comments)
                                @Popover("Other comments to the organizers", "Are you more than one speaker? Do you need special props? Anything else we should know about?")
                                @Html.TextAreaFor(m => m.Comments, new {@class = "form-control", rows = 6})
                                @Html.ValidationMessageFor(m => m.Comments)
                            </div>
                        </div>
                    </div>
                </div>
            </div>

        </div>
        <div class="panel-footer">
            <button type="submit" class="btn btn-primary">Save</button>
            @if (Model.Id != 0)
            {
                <a href="" class="btn btn-danger pull-right"
                   data-confirm-form="#deleteForm"
                   data-modal-title="Are you sure?"
                   data-modal-message="This will delete the session."
                   data-toggle="modal" data-target="#formConfirmationModal"><i class="glyphicon glyphicon-trash"></i>&nbsp;Delete</a>
            }
        </div>
    }

</div>

@using (Html.BeginForm("DeleteSession", "CallForPapers", new {confernceSlug = conference.Slug, id = Model.Id}, FormMethod.Post, new {id = "deleteForm", @class = "form-inline"}))
{

}

@section scripts
{
    <script type="text/javascript">
        $(function() {
            $('[data-toggle="popover"]').popover();
        });
    </script>
}