src/Swetugg.Web/Models/ImageType.cs
using System.ComponentModel.DataAnnotations;

namespace Swetugg.Web.Models
{
    public class ImageType
    {
        public int Id { get; set; }
        
        public int ConferenceId { get; set; }
        
        [Required]
        [StringLength(250)]
        public string Name { get; set; }

        [Required]
        [StringLength(250)]
        public string Slug { get; set; }

        public int? Width { get; set; }
        public int? Height { get; set; }

    }
}

src/Swetugg.Web/Models/Sponsor.cs
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Swetugg.Web.Models
{
    public class Sponsor
    {
        public int Id { get; set; }
        public int ConferenceId { get; set; }

        [Required]
        [StringLength(250)]
        public string Name { get; set; }

        [Required]
        [StringLength(250)]
        public string Slug { get; set; }

        [DataType(DataType.MultilineText)]
        [Column(TypeName = "ntext")]
        public string Description { get; set; }

        [StringLength(250)]
        public string Web { get; set; }

        [StringLength(50)]
        public string Twitter { get; set; }

        public bool Published { get; set; }

        public int Priority { get; set; }
        public ICollection<SponsorImage> Images { get; set; }
    }
}

src/Swetugg.Web/Areas/Admin/Controllers/SponsorAdminController.cs
using System;
using System.Configuration;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Swetugg.Web.Models;
using Swetugg.Web.Services;

namespace Swetugg.Web.Areas.Admin.Controllers
{
    public class SponsorAdminController : ConferenceAdminControllerBase
    {
        private readonly IImageUploader _imageUploader;
        private readonly string _sponsorImageContainerName;

        public SponsorAdminController(IImageUploader imageUploader, ApplicationDbContext dbContext) : base(dbContext)
        {
            _imageUploader = imageUploader;
            _sponsorImageContainerName = ConfigurationManager.AppSettings["Storage.Container.Sponsors.SponsorImages"];
        }

        [Route("{conferenceSlug}/sponsors")]
        public async Task<Microsoft.AspNetCore.Mvc.ActionResult> Index()
        {
            var conferenceId = ConferenceId;
            var sponsors = from s in dbContext.Sponsors
                           where s.ConferenceId == conferenceId
                           orderby s.Name
                           select s;

            var sponsorsList = await sponsors.ToListAsync();
            return View(sponsorsList);
        }

		[Route("{conferenceSlug}/sponsors/{id:int}")]
        public async Task<Microsoft.AspNetCore.Mvc.ActionResult> Sponsor(int id)
        {
            var conferenceId = ConferenceId;
            var sponsor = await dbContext.Sponsors
                .Include(sp => sp.Images.Select(i => i.ImageType))
                .SingleAsync(s => s.Id == id);
            
            var imageTypes = await dbContext.ImageTypes.Where(it => it.ConferenceId == conferenceId).ToListAsync();
            ViewBag.ImageTypes = imageTypes;

            return View(sponsor);
        }

		[Route("{conferenceSlug}/sponsors/edit/{id:int}", Order = 1)]
        public async Task<Microsoft.AspNetCore.Mvc.ActionResult> Edit(int id)
        {
            var sponsor = await dbContext.Sponsors.SingleAsync(s => s.Id == id);
            return View(sponsor);
        }

        [ValidateAntiForgeryToken]
        [HttpPost]
		[Route("{conferenceSlug}/sponsors/edit/{id:int}", Order = 1)]
        public async Task<Microsoft.AspNetCore.Mvc.ActionResult> Edit(int id, Sponsor sponsor)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    sponsor.ConferenceId = ConferenceId;
					dbContext.Entry(sponsor).State = EntityState.Modified;
					await dbContext.SaveChangesAsync();

                    return RedirectToAction("Sponsor", new { sponsor.Id });
                }
                catch (Exception ex)
                {
                    // TODO: Add model error
                    //ModelState.AddModelError("Updating", ex);
                }
            }
            return View(sponsor);
        }

		[Route("{conferenceSlug}/sponsors/new", Order = 2)]
        public Microsoft.AspNetCore.Mvc.ActionResult Edit()
        {
            return View();
        }

        [ValidateAntiForgeryToken]
        [HttpPost]
		[Route("{conferenceSlug}/sponsors/new", Order = 2)]
        public async Task<Microsoft.AspNetCore.Mvc.ActionResult> Edit(Sponsor sponsor)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    sponsor.ConferenceId = ConferenceId;
                    dbContext.Sponsors.Add(sponsor);
                    await dbContext.SaveChangesAsync();
                    return RedirectToAction("Sponsor", new { sponsor.Id });
                }
                catch (Exception ex)
                {
                    // TODO: Add model error
                    //ModelState.AddModelError("Updating", ex);
                }
            }
            return View(sponsor);
        }

        [Route("{conferenceSlug}/sponsors/{sponsorId:int}/image/{id:int}")]
        public async Task<Microsoft.AspNetCore.Mvc.ActionResult> Image(int sponsorId, int id)
        {
            var conferenceId = ConferenceId;
            var sponsor = await dbContext.Sponsors.Include(sp => sp.Images.Select(i => i.ImageType))
                .SingleAsync(s => s.Id == sponsorId);
            var imageTypes = await dbContext.ImageTypes.Where(it => it.ConferenceId == conferenceId).ToListAsync();

            var image = sponsor.Images.FirstOrDefault(i => i.Id == id);
            ViewBag.Sponsor = sponsor;
            ViewBag.ImageTypes = imageTypes;

            return View(image);
        }

        [ValidateAntiForgeryToken]
        [HttpPost]
        [Route("{conferenceSlug}/sponsors/{sponsorId:int}/image/new")]
        public async Task<Microsoft.AspNetCore.Mvc.ActionResult> NewImage(int sponsorId, SponsorImage sponsorImage, IFormFile imageFile)
        {
            var sponsor = await dbContext.Sponsors.Include(sp => sp.Images.Select(i => i.ImageType))
                .SingleAsync(s => s.Id == sponsorId);
            var imageType = await dbContext.ImageTypes.FirstOrDefaultAsync(it => it.Id == sponsorImage.ImageTypeId);

            if (imageType == null)
            {
                throw new InvalidOperationException("Unknown image type");
            }

            string errorMessage = null;

            if (imageFile != null && imageFile.Length > 0)
            {
                if (imageFile.Length < 10 * 1024 * 1024)
                {
                    try
                    {
                        string imageUrl;
                        using (var memStream = new MemoryStream())
                        {
                            imageFile.OpenReadStream().CopyTo(memStream);
                            imageUrl = await _imageUploader.UploadToStorage(memStream, sponsor.Slug + "-" + imageType.Slug,
                                _sponsorImageContainerName);
                        }

                        sponsorImage.ImageUrl = imageUrl;

                        sponsor.Images.Add(sponsorImage);
                        await dbContext.SaveChangesAsync();
                        return RedirectToAction("Sponsor", new { id = sponsorId });
                    }
                    catch (ImageUploadException e)
                    {
                        errorMessage = e.Message;
                        ModelState.AddModelError("ImageFile", e.Message);
                    }
                }
                else
                {
                    errorMessage = "Max file size of image is ~10MB";
                    ModelState.AddModelError("ImageFile", "Max file size of image is ~10MB");
                }
            }

            return RedirectToAction("Sponsor", new { id = sponsorId, errorMsg = errorMessage });
        }

        [ValidateAntiForgeryToken]
        [HttpPost]
        [Route("{conferenceSlug}/sponsors/{sponsorId:int}/image/{id:int}/delete")]
        public async Task<Microsoft.AspNetCore.Mvc.ActionResult> DeleteImage(int id, int sponsorId)
        {
            var sponsor = await dbContext.Sponsors.Include(sp => sp.Images.Select(i => i.ImageType))
                .SingleAsync(s => s.Id == sponsorId);
            var image = sponsor.Images.Single(i => i.Id == id);

            dbContext.Entry(image).State = EntityState.Deleted;
            _imageUploader.DeleteImage(image.ImageUrl);

            await dbContext.SaveChangesAsync();
            return RedirectToAction("Sponsor", new { id = sponsorId });
        }

        [ValidateAntiForgeryToken]
        [HttpPost]
        [Route("{conferenceSlug}/sponsors/delete/{id:int}")]
        public async Task<Microsoft.AspNetCore.Mvc.ActionResult> Delete(int id)
        {
            var sponsor = await dbContext.Sponsors.SingleAsync(sp => sp.Id == id);

            dbContext.Entry(sponsor).State = EntityState.Deleted;

            await dbContext.SaveChangesAsync();
            
            return RedirectToAction("Index");

        }
    }
}

src/Swetugg.Web/Areas/Admin/Views/SponsorAdmin/Edit.cshtml
@using Swetugg.Web.Models
@model Sponsor
@Html.AntiForgeryToken()
@{
    ViewBag.Title = "Sponsor - Edit";
    Conference conference = ViewBag.Conference;
    var buttonLabel = "Create";

    var id = Model != null && Model.Id != 0 ? (int?)Model.Id : null;
    if (id != null)
    {
        buttonLabel = "Update";
    }
}

<ol class="breadcrumb">
    <li>@Html.ActionLink("Start", "Start", "Home", new { Area = "" }, null)</li>
    <li>@Html.ActionLink("Conferences", "Index", "ConferenceAdmin")</li>
    <li>@Html.ActionLink(conference.Name, "Conference", "ConferenceAdmin", new { conference.Id }, null)</li>
    <li>@Html.ActionLink("Sponsors", "Index", "SponsorAdmin")</li>
    @if (id != null)
    {
        <li>@Html.ActionLink(Model.Name, "Sponsor", "SponsorAdmin", new { id })</li>
    }
    <li class="active">@buttonLabel</li>
</ol>

<div class="panel panel-default">
    <div class="panel-heading">
        <h3>Sponsor</h3>
    </div>
    @using (Html.BeginForm("Edit", "SponsorAdmin", new { id }, FormMethod.Post))
    {
        @Html.AntiForgeryToken()
        <div class="panel-body">
            <div class="row">
                <div class="col-sm-8">
                    <div class="form-group">
                        @Html.LabelFor(m => m.Name)
                        @Html.TextBoxFor(m => m.Name, new { @class = "form-control" })
                    </div>
                    <div class="form-group">
                        @Html.LabelFor(m => m.Twitter)
                        <div class="input-group">
                            <div class="input-group-addon">@@</div>
                            @Html.TextBoxFor(m => m.Twitter, new { @class = "form-control" })
                        </div>
                    </div>
                    <div class="form-group">
                        @Html.LabelFor(m => m.Web)
                        @Html.TextBoxFor(m => m.Web, new { @class = "form-control" })
                    </div>
                    <div class="form-group">
                        @Html.LabelFor(m => m.Description)
                        @Html.TextAreaFor(m => m.Description, new { @class = "form-control", rows = 10 })
                    </div>
                </div>
                <div class="col-sm-4">
                    <div class="panel panel-info">
                        <div class="panel-heading">
                            <div class="panel-title">
                                Publish settings
                            </div>
                        </div>
                        <div class="panel-body">
                            <div class="form-group">
                                <div class="checkbox">
                                    <label>
                                        @Html.CheckBoxFor(m => m.Published)
                                        @Html.DisplayNameFor(m => m.Published)
                                    </label>
                                </div>
                            </div>
                            <div class="form-group">
                                @Html.LabelFor(m => m.Slug)
                                @Html.TextBoxFor(m => m.Slug, new { @class = "form-control" })
                            </div>
                            <div class="form-group">
                                @Html.LabelFor(m => m.Priority, "Priority")
                                @Html.TextBoxFor(m => m.Priority, new { @class = "form-control" })
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="panel-footer">
            <button type="submit" class="btn btn-primary">@buttonLabel</button>
        </div>
    }
</div>

src/Swetugg.Web/Areas/Admin/Views/SponsorAdmin/Image.cshtml
@using Swetugg.Web.Models
@model SponsorImage
@Html.AntiForgeryToken()
@{
    ViewBag.Title = "Sponsor Image - Edit";
    Conference conference = ViewBag.Conference;

    var sponsor = (Sponsor)ViewBag.Sponsor;

}

<ol class="breadcrumb">
    <li>@Html.ActionLink("Start", "Start", "Home", new { Area = "" }, null)</li>
    <li>@Html.ActionLink("Conferences", "Index", "ConferenceAdmin")</li>
    <li>@Html.ActionLink(conference.Name, "Conference", "ConferenceAdmin", new { conference.Id }, null)</li>
    <li>@Html.ActionLink("Sponsors", "Index", "SponsorAdmin")</li>
    <li>@Html.ActionLink(sponsor.Name, "Sponsor", "SponsorAdmin", new { sponsor.Id }, null)</li>
    <li class="active">Image</li>
</ol>

@Html.ValidationSummary()
<div class="panel panel-default">
    <div class="panel-heading">
        <h3>Sponsor image</h3>
    </div>
    <div class="panel-body">
        <div class="row">
            <div class="col-sm-8">
                <img src="@Model.ImageUrl" style="width: 100%" />
            </div>

            <div class="col-sm-4">
                <div class="panel panel-info">
                    <div class="panel-heading">
                        <div class="panel-title">Image info</div>
                    </div>
                    <div class="panel-body">
                        <dl>
                            <dt>Image type</dt>
                            <dd>@Model.ImageType.Name</dd>
                            <dt>Url</dt>
                            <dd><input type="text" class="form-control" readonly="readonly" value="@Model.ImageUrl" /></dd>
                            @if (Model.ImageType.Width.HasValue)
                            {
                                <dt>Width</dt>
                                <dd>@(Model.ImageType.Width)</dd>
                            }
                            @if (Model.ImageType.Height.HasValue)
                            {
                                <dt>Height</dt>
                                <dd>@(Model.ImageType.Height)</dd>
                            }
                        </dl>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="panel-footer text-right">
        <a href="" class="btn btn-danger"
           data-confirm-form="#deleteImageForm"
           data-modal-title="Are you sure?"
           data-modal-message="This will delete the image."
           data-toggle="modal" data-target="#formConfirmationModal"><i class="glyphicon glyphicon-trash"></i>&nbsp;Delete</a>


        @using (Html.BeginForm("DeleteImage", "SponsorAdmin", new { id = Model.Id, SponsorId = sponsor.Id }, FormMethod.Post, true, new { @class = "pull-right", id = "deleteImageForm" }))
        {
            @Html.AntiForgeryToken()
        }
    </div>
</div>

src/Swetugg.Web/Areas/Admin/Views/SponsorAdmin/Index.cshtml
@using Swetugg.Web.Models
@model List<Sponsor>
@Html.AntiForgeryToken()
@{
    Conference conference = ViewBag.Conference;
    ViewBag.Title = "Sponsors";
}

<ol class="breadcrumb">
    <li>@Html.ActionLink("Start", "Start", "Home", new { Area = "" }, null)</li>
    <li>@Html.ActionLink("Conferences", "Index", "ConferenceAdmin")</li>
    <li>@Html.ActionLink(conference.Name, "Conference", "ConferenceAdmin", new { conference.Id }, null)</li>
    <li class="active">Sponsors</li>
</ol>

<div class="panel panel-default">
    <div class="panel-heading">
        <div class="row">
            <div class="col-md-8">
                <h3>Sponsors</h3>
            </div>
            <div class="col-md-4">
                <dl class="dl-horizontal">
                    <dt>Published</dt>
                    <dd>@Model.Count(m => m.Published)</dd>
                    <dt>Total</dt>
                    <dd>@Model.Count()</dd>
                </dl>
            </div>
        </div>
    </div>
    <div class="list-group">
        @foreach (var sponsor in Model)
        {
            <a href="@Url.Action("Sponsor", new { id = sponsor.Id })" class="list-group-item">
                @await Html.PartialAsync("_PublishedIcon", sponsor.Published)
                @sponsor.Name
            </a>
        }
    </div>
</div>
@Html.ActionLink("New sponsor", "Edit", new { }, new { @class = "btn btn-primary" })

src/Swetugg.Web/Areas/Admin/Views/SponsorAdmin/Sponsor.cshtml
@using System.Globalization
@using Swetugg.Web.Models
@model Sponsor
@Html.AntiForgeryToken()
@{
    ViewBag.Title = "Sponsor";
    Conference conference = ViewBag.Conference;
    var imageTypes = (IEnumerable<ImageType>)ViewBag.ImageTypes;
    var errorMsg = ViewBag.ErrorMessage;
}
<ol class="breadcrumb">
    <li>@Html.ActionLink("Start", "Start", "Home", new { Area = "" }, null)</li>
    <li>@Html.ActionLink("Conferences", "Index", "ConferenceAdmin")</li>
    <li>@Html.ActionLink(conference.Name, "Conference", "ConferenceAdmin", new { conference.Id }, null)</li>
    <li>@Html.ActionLink("Sponsors", "Index")</li>
    <li class="active">@Model.Name</li>
</ol>

<div class="panel panel-default">
    <div class="panel-heading">
        <h3>
            @await Html.PartialAsync("_PublishedIcon", Model.Published)
            @Model.Name
        </h3>
    </div>
    <div class="panel-body">
        <div class="row">
            <div class="col-sm-8">
                <p>@Model.Description</p>
            </div>
            <div class="col-sm-4">
                <div class="panel panel-info">
                    <div class="panel-heading">
                        <div class="panel-title">Images</div>
                    </div>
                    <div class="list-group">
                        @foreach (var image in Model.Images)
                        {
                            <div class="list-group-item">
                                @Html.ActionLink(image.ImageType.Name, "Image", "SponsorAdmin", new { image.Id, SponsorId = Model.Id }, null)
                            </div>
                        }
                    </div>
                    <div class="panel-footer">
                        @using (Html.BeginForm("NewImage", "SponsorAdmin", new { SponsorId = Model.Id }, FormMethod.Post, true, new { enctype = "multipart/form-data" }))
                        {
                            @Html.AntiForgeryToken()
                            <div class="form-group">
                                @Html.DropDownList("ImageTypeId",
                                    imageTypes.Select(it => new SelectListItem() { Text = it.Name, Value = it.Id.ToString(CultureInfo.InvariantCulture) }),
                                    new { @class = "form-control" })
                            </div>
                            <div class="row">
                                <div class="col-sm-6">
                                    <div class="form-group">
                                        <label class="btn btn-default" for="imageFileSelector">
                                            <input id="imageFileSelector" name="ImageFile" type="file" style="display: none;">
                                            Select image...
                                        </label>
                                    </div>
                                </div>
                                <div class="col-sm-6">
                                    <button class="btn btn-primary" type="submit">Upload</button>
                                </div>
                            </div>
                        }
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="panel-footer">
        @Html.ActionLink("Edit", "Edit", new { id = Model.Id }, new { @class = "btn btn-default" })

        <a href="" class="btn btn-danger pull-right"
           data-confirm-form="#deleteSponsorForm"
           data-modal-title="Are you sure?"
           data-modal-message="This will delete the sponsor."
           data-toggle="modal" data-target="#formConfirmationModal"><i class="glyphicon glyphicon-trash"></i>&nbsp;Delete</a>

        @using (Html.BeginForm("Delete", "SponsorAdmin", new { id = Model.Id }, FormMethod.Post, true, new { @class = "pull-right", id = "deleteSponsorForm" }))
        {
            @Html.AntiForgeryToken()
        }
    </div>
</div>