src/Swetugg.Web/Areas/Admin/Controllers/SessionTypeAdminController.cs
using System;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Swetugg.Web.Models;

namespace Swetugg.Web.Areas.Admin.Controllers
{
    public class SessionTypeAdminController : ConferenceAdminControllerBase
    {
        public SessionTypeAdminController(ApplicationDbContext dbContext)
            : base(dbContext)
        {
        }

        [Route("{conferenceSlug}/session-types")]
        public async Task<Microsoft.AspNetCore.Mvc.ActionResult> Index()
        {
            var conferenceId = ConferenceId;
            var sessionTypes = from s in dbContext.SessionTypes
                where s.ConferenceId == conferenceId
                orderby s.Priority
                select s;
            var sessionTypeList = await sessionTypes.ToListAsync();

            return View(sessionTypeList);
        }

        [Route("{conferenceSlug}/session-types/edit/{id:int}", Order = 1)]
        public async Task<Microsoft.AspNetCore.Mvc.ActionResult> Edit(int id)
        {
            var sessionType = await dbContext.SessionTypes.SingleAsync(s => s.Id == id);
            return View(sessionType);
        }

        [ValidateAntiForgeryToken]
        [HttpPost]
        [Route("{conferenceSlug}/session-types/edit/{id:int}", Order = 1)]
        public async Task<Microsoft.AspNetCore.Mvc.ActionResult> Edit(int id, SessionType sessionType)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    sessionType.ConferenceId = ConferenceId;
                    dbContext.Entry(sessionType).State = EntityState.Modified;
                    await dbContext.SaveChangesAsync();

                    return RedirectToAction("Index");
                }
                catch (Exception ex)
                {
                    // TODO: Add model error
                    //ModelState.AddModelError("Updating", ex);
                }
            }
            return View(sessionType);
        }

        [Route("{conferenceSlug}/session-types/new", Order = 2)]
        public Microsoft.AspNetCore.Mvc.ActionResult Edit()
        {
            return View();
        }

        [ValidateAntiForgeryToken]
        [HttpPost]
        [Route("{conferenceSlug}/session-types/new", Order = 2)]
        public async Task<Microsoft.AspNetCore.Mvc.ActionResult> Edit(SessionType sessionType)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    sessionType.ConferenceId = ConferenceId;
                    dbContext.SessionTypes.Add(sessionType);
                    await dbContext.SaveChangesAsync();
                    return RedirectToAction("Index");
                }
                catch (Exception ex)
                {
                    // TODO: Add model error
                    //ModelState.AddModelError("Updating", ex);
                }
            }
            return View(sessionType);
        }

    }
}

src/Swetugg.Web/Areas/Admin/Views/SessionTypeAdmin/Edit.cshtml
@using Swetugg.Web.Models
@model SessionType
@{
    ViewBag.Title = "Session Type - Edit";
    Conference conference = ViewBag.Conference;
    var buttonLabel = "Create";

    var id = Model != null && Model.Id != 0 ? (int?)Model.Id : null;
    if (id != null)
    {
        buttonLabel = "Update";
    }
}

<ol class="breadcrumb">
    <li>@Html.ActionLink("Start", "Start", "Home", new { Area = "" }, null)</li>
    <li>@Html.ActionLink("Conferences", "Index", "ConferenceAdmin")</li>
    <li>@Html.ActionLink(conference.Name, "Conference", "ConferenceAdmin", new { conference.Id }, null)</li>
    <li>@Html.ActionLink("Session types", "Index", "SessionTypeAdmin")</li>
    <li class="active">@buttonLabel</li>
</ol>

<div class="panel panel-default">
    <div class="panel-heading">
        <h3>Session type</h3>
    </div>
    @using (Html.BeginForm("Edit", "SessionTypeAdmin", new { id }, FormMethod.Post))
    {
        @Html.AntiForgeryToken()
        <div class="panel-body">
            <div class="row">
                <div class="col-sm-8">
                    <div class="form-group">
                        @Html.LabelFor(m => m.Name)
                        @Html.TextBoxFor(m => m.Name, new { @class = "form-control" })
                        @Html.ValidationMessageFor(m => m.Name)
                    </div>
                    <div class="form-group">
                        @Html.LabelFor(m => m.Description)
                        @Html.TextAreaFor(m => m.Description, new { @class = "form-control", rows = 10 })
                    </div>
                </div>
                <div class="col-sm-4">
                    <div class="panel panel-info">
                        <div class="panel-heading">
                            <div class="panel-title">
                                Publish settings
                            </div>
                        </div>
                        <div class="panel-body">
                            <div class="form-group">
                                @Html.LabelFor(m => m.Slug)
                                @Html.TextBoxFor(m => m.Slug, new { @class = "form-control" })
                                @Html.ValidationMessageFor(m => m.Slug)
                            </div>
                            <div class="form-group">
                                @Html.LabelFor(m => m.Priority, "Priority")
                                @Html.TextBoxFor(m => m.Priority, new { @class = "form-control" })
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="panel-footer">
            <button type="submit" class="btn btn-primary">@buttonLabel</button>
        </div>
    }
</div>

src/Swetugg.Web/Areas/Admin/Views/SessionTypeAdmin/Index.cshtml
@using Swetugg.Web.Models
@model List<SessionType>
@Html.AntiForgeryToken()
@{
    ViewBag.Title = "Session types";
    Conference conference = ViewBag.Conference;
}

<ol class="breadcrumb">
    <li>@Html.ActionLink("Start", "Start", "Home", new { Area = "" }, null)</li>
    <li>@Html.ActionLink("Conferences", "Index", "ConferenceAdmin")</li>
    <li>@Html.ActionLink(conference.Name, "Conference", "ConferenceAdmin", new { conference.Id }, null)</li>
    <li class="active">Session Types</li>
</ol>

<h2>Image Types</h2>
<div class="list-group">
    @foreach (var sessionType in Model)
    {
        @Html.ActionLink(sessionType.Name, "Edit", new { id = sessionType.Id }, new { @class = "list-group-item" })
    }
</div>

@Html.ActionLink("New session type", "Edit", new { }, new { @class = "btn btn-primary" })