src/Swetugg.Web/Areas/Admin/Controllers/ImageTypeAdminController.cs
using System;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Swetugg.Web.Models;

namespace Swetugg.Web.Areas.Admin.Controllers
{
    public class ImageTypeAdminController : ConferenceAdminControllerBase
    {
        public ImageTypeAdminController(ApplicationDbContext dbContext)
            : base(dbContext)
        {
        }

        [Route("{conferenceSlug}/image-types")]
        public async Task<Microsoft.AspNetCore.Mvc.ActionResult> Index()
        {
            var conferenceId = ConferenceId;
            var imageTypes = from s in dbContext.ImageTypes
                where s.ConferenceId == conferenceId
                select s;
            var imageTypeList = await imageTypes.ToListAsync();

            return View(imageTypeList);
        }

        [Route("{conferenceSlug}/image-types/edit/{id:int}", Order = 1)]
        public async Task<Microsoft.AspNetCore.Mvc.ActionResult> Edit(int id)
        {
            var imageType = await dbContext.ImageTypes.SingleAsync(s => s.Id == id);
            return View(imageType);
        }

        [ValidateAntiForgeryToken]
        [HttpPost]
        [Route("{conferenceSlug}/image-types/edit/{id:int}", Order = 1)]
        public async Task<Microsoft.AspNetCore.Mvc.ActionResult> Edit(int id, ImageType imageType)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    imageType.ConferenceId = ConferenceId;
                    dbContext.Entry(imageType).State = EntityState.Modified;
                    await dbContext.SaveChangesAsync();

                    return RedirectToAction("Index");
                }
                catch (Exception ex)
                {
                    // TODO: Add model error
                    //ModelState.AddModelError("Updating", ex);
                }
            }
            return View(imageType);
        }

        [Route("{conferenceSlug}/image-types/new", Order = 2)]
        public Microsoft.AspNetCore.Mvc.ActionResult Edit()
        {
            return View();
        }

        [ValidateAntiForgeryToken]
        [HttpPost]
        [Route("{conferenceSlug}/image-types/new", Order = 2)]
        public async Task<Microsoft.AspNetCore.Mvc.ActionResult> Edit(ImageType imageType)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    imageType.ConferenceId = ConferenceId;
                    dbContext.ImageTypes.Add(imageType);
                    await dbContext.SaveChangesAsync();
                    return RedirectToAction("Index");
                }
                catch (Exception ex)
                {
                    // TODO: Add model error
                    //ModelState.AddModelError("Updating", ex);
                }
            }
            return View(imageType);
        }

    }
}

src/Swetugg.Web/Areas/Admin/Views/ImageTypeAdmin/Edit.cshtml
@using Swetugg.Web.Models
@Html.AntiForgeryToken()
@model ImageType

@{
    ViewBag.Title = "Image Type - Edit";
    Conference conference = ViewBag.Conference;
    var buttonLabel = "Create";

    var id = Model != null && Model.Id != 0 ? (int?)Model.Id : null;
    if (id != null)
    {
        buttonLabel = "Update";
    }
}

<ol class="breadcrumb">
    <li>@Html.ActionLink("Start", "Start", "Home", new { Area = "" }, null)</li>
    <li>@Html.ActionLink("Conferences", "Index", "ConferenceAdmin")</li>
    <li>@Html.ActionLink(conference.Name, "Conference", "ConferenceAdmin", new { conference.Id }, null)</li>
    <li>@Html.ActionLink("Image types", "Index", "ImageTypeAdmin")</li>
    <li class="active">@buttonLabel</li>
</ol>

<div class="panel panel-default">
    <div class="panel-heading">
        <h3>Image type</h3>
    </div>
    @using (Html.BeginForm("Edit", "ImageTypeAdmin", new { id }, FormMethod.Post))
    {
        @Html.AntiForgeryToken()
        <div class="panel-body">
            <div class="row">
                <div class="col-sm-8">
                    <div class="form-group">
                        @Html.LabelFor(m => m.Name)
                        @Html.TextBoxFor(m => m.Name, new { @class = "form-control" })
                        @Html.ValidationMessageFor(m => m.Name)
                    </div>
                    <div class="row">
                        <div class="col-xs-6 col-sm-4">
                            <div class="form-group">
                                @Html.LabelFor(m => m.Width)
                                @Html.TextBoxFor(m => m.Width, new { @class = "form-control" })
                                @Html.ValidationMessageFor(m => m.Width)
                            </div>
                        </div>
                        <div class="col-xs-6 col-sm-4">
                            <div class="form-group">
                                @Html.LabelFor(m => m.Height)
                                @Html.TextBoxFor(m => m.Height, new { @class = "form-control" })
                                @Html.ValidationMessageFor(m => m.Height)
                            </div>
                        </div>
                    </div>
                </div>
                <div class="col-sm-4">
                    <div class="panel panel-info">
                        <div class="panel-heading">
                            <div class="panel-title">
                                Publish settings
                            </div>
                        </div>
                        <div class="panel-body">
                            <div class="form-group">
                                @Html.LabelFor(m => m.Slug)
                                @Html.TextBoxFor(m => m.Slug, new { @class = "form-control" })
                                @Html.ValidationMessageFor(m => m.Slug)
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="panel-footer">
            <button type="submit" class="btn btn-primary">@buttonLabel</button>
        </div>
    }
</div>

src/Swetugg.Web/Areas/Admin/Views/ImageTypeAdmin/Index.cshtml
@using Swetugg.Web.Models
@Html.AntiForgeryToken()
@model List<ImageType>
@{
    ViewBag.Title = "Image types";
    Conference conference = ViewBag.Conference;
}

<ol class="breadcrumb">
    <li>@Html.ActionLink("Start", "Start", "Home", new { Area = "" }, null)</li>
    <li>@Html.ActionLink("Conferences", "Index", "ConferenceAdmin")</li>
    <li>@Html.ActionLink(conference.Name, "Conference", "ConferenceAdmin", new { conference.Id }, null)</li>
    <li class="active">Image Types</li>
</ol>

<h2>Image Types</h2>
<div class="list-group">
    @foreach (var imageType in Model)
    {
        @Html.ActionLink(imageType.Name, "Edit", new { id = imageType.Id }, new { @class = "list-group-item" })
    }
</div>

@Html.ActionLink("New image type", "Edit", new { }, new { @class = "btn btn-primary" })